# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from sql_utils.sqlQuery import SqlQuery
import widgets.login
import os
from sql_utils.user import User
from crypto.crypto import Crypto
class Ui_MessageMain(QtWidgets.QDialog):
    def __init__(self,user:User):
        self.user = user
        super(Ui_MessageMain, self).__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self,self.user)

class Ui_Dialog(object):
    def setupUi(self, Dialog,user:User):
        self.user = user
        Dialog.setObjectName("Dialog")
        Dialog.resize(1070, 858)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblUser = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblUser.setFont(font)
        self.lblUser.setObjectName("lblUser")
        self.horizontalLayout.addWidget(self.lblUser)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bntQuit = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bntQuit.setFont(font)
        self.bntQuit.setObjectName("bntQuit")
        self.horizontalLayout.addWidget(self.bntQuit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 4)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.menu = QtWidgets.QFrame(Dialog)
        self.menu.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.menu.setObjectName("menu")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_14.setSpacing(12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btnPageSendMessage = QtWidgets.QPushButton(self.menu)
        self.btnPageSendMessage.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnPageSendMessage.setFont(font)
        self.btnPageSendMessage.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btnPageSendMessage.setObjectName("btnPageSendMessage")
        self.horizontalLayout_15.addWidget(self.btnPageSendMessage)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.btnPageOutbox = QtWidgets.QPushButton(self.menu)
        self.btnPageOutbox.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnPageOutbox.setFont(font)
        self.btnPageOutbox.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btnPageOutbox.setObjectName("btnPageOutbox")
        self.horizontalLayout_15.addWidget(self.btnPageOutbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.btnPageInbox = QtWidgets.QPushButton(self.menu)
        self.btnPageInbox.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnPageInbox.setFont(font)
        self.btnPageInbox.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btnPageInbox.setObjectName("btnPageInbox")
        self.horizontalLayout_15.addWidget(self.btnPageInbox)
        self.horizontalLayout_15.setStretch(0, 30)
        self.horizontalLayout_15.setStretch(1, 5)
        self.horizontalLayout_15.setStretch(2, 30)
        self.horizontalLayout_15.setStretch(3, 5)
        self.horizontalLayout_15.setStretch(4, 30)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.verticalLayout_2.addWidget(self.menu)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageSendMessage = QtWidgets.QWidget()
        self.pageSendMessage.setObjectName("pageSendMessage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pageSendMessage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.lblAdd = QtWidgets.QLabel(self.pageSendMessage)
        self.lblAdd.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblAdd.setFont(font)
        self.lblAdd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAdd.setObjectName("lblAdd")
        self.horizontalLayout_4.addWidget(self.lblAdd)
        self.btnAddFile = QtWidgets.QPushButton(self.pageSendMessage)
        self.btnAddFile.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAddFile.setFont(font)
        self.btnAddFile.setObjectName("btnAddFile")
        self.horizontalLayout_4.addWidget(self.btnAddFile)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.pageSendMessage)
        self.label.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cbTowho = QtWidgets.QComboBox(self.pageSendMessage)
        self.cbTowho.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbTowho.setFont(font)
        self.cbTowho.setObjectName("cbTowho")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbTowho)
        self.label_2 = QtWidgets.QLabel(self.pageSendMessage)
        self.label_2.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineTitle = QtWidgets.QLineEdit(self.pageSendMessage)
        self.lineTitle.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineTitle.setFont(font)
        self.lineTitle.setText("")
        self.lineTitle.setObjectName("lineTitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineTitle)
        self.textMessage = QtWidgets.QTextEdit(self.pageSendMessage)
        self.textMessage.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textMessage.setFont(font)
        self.textMessage.setObjectName("textMessage")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textMessage)
        self.horizontalLayout_14.addLayout(self.formLayout)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.horizontalLayout_14.setStretch(0, 10)
        self.horizontalLayout_14.setStretch(1, 90)
        self.horizontalLayout_14.setStretch(2, 20)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.btnEncrypt = QtWidgets.QPushButton(self.pageSendMessage)
        self.btnEncrypt.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEncrypt.setFont(font)
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.horizontalLayout_2.addWidget(self.btnEncrypt)
        self.btnSign = QtWidgets.QPushButton(self.pageSendMessage)
        self.btnSign.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSign.setFont(font)
        self.btnSign.setObjectName("btnSign")
        self.horizontalLayout_2.addWidget(self.btnSign)
        self.btnEncryptSign = QtWidgets.QPushButton(self.pageSendMessage)
        self.btnEncryptSign.setMinimumSize(QtCore.QSize(220, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEncryptSign.setFont(font)
        self.btnEncryptSign.setObjectName("btnEncryptSign")
        self.horizontalLayout_2.addWidget(self.btnEncryptSign)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.lblInfo = QtWidgets.QLabel(self.pageSendMessage)
        self.lblInfo.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblInfo.setFont(font)
        self.lblInfo.setText("")
        self.lblInfo.setObjectName("lblInfo")
        self.horizontalLayout_16.addWidget(self.lblInfo)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 70)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(4, 20)
        self.verticalLayout_10.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.pageSendMessage)
        self.pageInbox = QtWidgets.QWidget()
        self.pageInbox.setObjectName("pageInbox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageInbox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.menu_2 = QtWidgets.QFrame(self.pageInbox)
        self.menu_2.setStyleSheet("background-color: rgb(0,0,0);")
        self.menu_2.setObjectName("menu_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu_2)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listInbox = QtWidgets.QListWidget(self.menu_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dig2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.listInbox.setFont(font)
        self.listInbox.setStyleSheet("QListWidget {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dig2\";\n"
"\n"
"}\n"
"QListWidget::item\n"
"{\n"
"    border: 0px solid;\n"
"    border-radius:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"   background-color:rgb(170, 170, 255) ;\n"
"    color:rgb(0,0,0);\n"
"}\n"
"QListWidget::item:hover\n"
"{\n"
"   background-color:rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.listInbox.setObjectName("listInbox")
        self.verticalLayout_3.addWidget(self.listInbox)
        self.horizontalLayout_7.addWidget(self.menu_2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setVerticalSpacing(7)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.pageInbox)
        self.label_5.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineInDate = QtWidgets.QLineEdit(self.pageInbox)
        self.lineInDate.setReadOnly(True)
        self.lineInDate.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineInDate.setFont(font)
        self.lineInDate.setText("")
        self.lineInDate.setObjectName("lineInDate")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineInDate)
        self.label_6 = QtWidgets.QLabel(self.pageInbox)
        self.label_6.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineInTitle = QtWidgets.QLineEdit(self.pageInbox)
        self.lineInTitle.setReadOnly(True)
        self.lineInTitle.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineInTitle.setFont(font)
        self.lineInTitle.setText("")
        self.lineInTitle.setObjectName("lineInTitle")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineInTitle)
        self.textInMessage = QtWidgets.QTextEdit(self.pageInbox)
        self.textInMessage.setReadOnly(True)
        self.textInMessage.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textInMessage.setFont(font)
        self.textInMessage.setObjectName("textInMessage")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textInMessage)
        self.lineInFromTo = QtWidgets.QLineEdit(self.pageInbox)
        self.lineInFromTo.setReadOnly(True)
        self.lineInFromTo.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineInFromTo.setFont(font)
        self.lineInFromTo.setText("")
        self.lineInFromTo.setObjectName("lineInFromTo")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineInFromTo)
        self.label_9 = QtWidgets.QLabel(self.pageInbox)
        self.label_9.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.btnDecrypt = QtWidgets.QPushButton(self.pageInbox)
        self.btnDecrypt.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDecrypt.setFont(font)
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.horizontalLayout_5.addWidget(self.btnDecrypt)
        self.btnVerify = QtWidgets.QPushButton(self.pageInbox)
        self.btnVerify.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnVerify.setFont(font)
        self.btnVerify.setObjectName("btnVerify")
        self.horizontalLayout_5.addWidget(self.btnVerify)
        self.btnVerifyDecrypt = QtWidgets.QPushButton(self.pageInbox)
        self.btnVerifyDecrypt.setMinimumSize(QtCore.QSize(220, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnVerifyDecrypt.setFont(font)
        self.btnVerifyDecrypt.setObjectName("btnVerifyDecrypt")
        self.horizontalLayout_5.addWidget(self.btnVerifyDecrypt)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.horizontalLayout_5.setStretch(0, 8)
        self.horizontalLayout_5.setStretch(1, 6)
        self.horizontalLayout_5.setStretch(2, 6)
        self.horizontalLayout_5.setStretch(3, 6)
        self.horizontalLayout_5.setStretch(4, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.btnInOpenAttachment = QtWidgets.QPushButton(self.pageInbox)
        self.btnInOpenAttachment.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnInOpenAttachment.setFont(font)
        self.btnInOpenAttachment.setObjectName("btnInOpenAttachment")
        self.horizontalLayout_3.addWidget(self.btnInOpenAttachment)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.horizontalLayout_3.setStretch(0, 56)
        self.horizontalLayout_3.setStretch(1, 32)
        self.horizontalLayout_3.setStretch(2, 48)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem19)
        self.lblInInfo = QtWidgets.QLabel(self.pageInbox)
        self.lblInInfo.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblInInfo.setFont(font)
        self.lblInInfo.setStyleSheet("")
        self.lblInInfo.setText("")
        self.lblInInfo.setObjectName("lblInInfo")
        self.horizontalLayout_6.addWidget(self.lblInInfo)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem21)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem22)
        self.horizontalLayout_7.setStretch(0, 40)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 150)
        self.horizontalLayout_7.setStretch(3, 20)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.stackedWidget.addWidget(self.pageInbox)
        self.pageOutbox = QtWidgets.QWidget()
        self.pageOutbox.setObjectName("pageOutbox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageOutbox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.menu_3 = QtWidgets.QFrame(self.pageOutbox)
        self.menu_3.setStyleSheet("background-color: rgba(0,0,0);")
        self.menu_3.setObjectName("menu_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.menu_3)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listOutbox = QtWidgets.QListWidget(self.menu_3)
        self.listOutbox.setMinimumSize(QtCore.QSize(160, 548))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dig2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.listOutbox.setFont(font)
        self.listOutbox.setStyleSheet("QListWidget {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dig2\";\n"
"\n"
"}\n"
"QListWidget::item\n"
"{\n"
"    border: 0px solid;\n"
"    border-radius:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"   background-color:rgb(170, 170, 255) ;\n"
"    color:rgb(0,0,0);\n"
"}\n"
"QListWidget::item:hover\n"
"{\n"
"   background-color:rgb(85, 170, 255);\n"
"    color:rgb(0,0,0);\n"
"}")
        self.listOutbox.setObjectName("listOutbox")
        self.verticalLayout_5.addWidget(self.listOutbox)
        self.horizontalLayout_11.addWidget(self.menu_3)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.pageOutbox)
        self.label_7.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineOutDate = QtWidgets.QLineEdit(self.pageOutbox)
        self.lineOutDate.setReadOnly(True)
        self.lineOutDate.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineOutDate.setFont(font)
        self.lineOutDate.setText("")
        self.lineOutDate.setObjectName("lineOutDate")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineOutDate)
        self.label_8 = QtWidgets.QLabel(self.pageOutbox)
        self.label_8.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineOutTitle = QtWidgets.QLineEdit(self.pageOutbox)
        self.lineOutTitle.setReadOnly(True)
        self.lineOutTitle.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineOutTitle.setFont(font)
        self.lineOutTitle.setText("")
        self.lineOutTitle.setObjectName("lineOutTitle")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineOutTitle)
        self.textOutMessage = QtWidgets.QTextEdit(self.pageOutbox)
        self.textOutMessage.setReadOnly(True)
        self.textOutMessage.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textOutMessage.setFont(font)
        self.textOutMessage.setObjectName("textOutMessage")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textOutMessage)
        self.lineOutToWho = QtWidgets.QLineEdit(self.pageOutbox)
        self.lineOutToWho.setReadOnly(True)
        self.lineOutToWho.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineOutToWho.setFont(font)
        self.lineOutToWho.setText("")
        self.lineOutToWho.setObjectName("lineOutToWho")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineOutToWho)
        self.label_10 = QtWidgets.QLabel(self.pageOutbox)
        self.label_10.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.verticalLayout_6.addLayout(self.formLayout_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem24)
        self.btnOutOpenAttachment = QtWidgets.QPushButton(self.pageOutbox)
        self.btnOutOpenAttachment.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnOutOpenAttachment.setFont(font)
        self.btnOutOpenAttachment.setObjectName("btnOutOpenAttachment")
        self.horizontalLayout_10.addWidget(self.btnOutOpenAttachment)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem25)
        self.horizontalLayout_10.setStretch(0, 20)
        self.horizontalLayout_10.setStretch(1, 10)
        self.horizontalLayout_10.setStretch(2, 15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem26)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem27)
        self.horizontalLayout_11.setStretch(0, 40)
        self.horizontalLayout_11.setStretch(1, 1)
        self.horizontalLayout_11.setStretch(2, 150)
        self.horizontalLayout_11.setStretch(3, 20)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.stackedWidget.addWidget(self.pageOutbox)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.lineTitle.setMaxLength(50)
        self.lblUser.setText(f"User : {self.user.user_name}")
        self.login = widgets.login.Ui_Login()
        self.crypto = Crypto()
        self.attachment_path = None
        self.message = None
        self.textMessage.setPlaceholderText("Enter your message..")
        # init functions
        self.fillUsersToComboBox()  # cbToWho
        self.listInbox.currentItemChanged.connect(self.displayInbox)
        self.listOutbox.currentItemChanged.connect(self.displayOutbox)
        # Connect Menu Buttons to Pages
        self.btnPageSendMessage.clicked.connect(self.goMessagePage)
        self.btnPageOutbox.clicked.connect(self.goOutboxPage)
        self.btnPageInbox.clicked.connect(self.goInboxPage)
        # Connect Send Message Page Buttons to func
        self.btnAddFile.clicked.connect(self.addFile)
        self.btnSign.clicked.connect(lambda : self.send("s"))
        self.btnEncrypt.clicked.connect(lambda : self.send("e"))
        self.btnEncryptSign.clicked.connect(lambda : self.send("se"))
        # Connect Inbox Page Buttons to func
        self.btnVerify.clicked.connect(lambda : self.get("v"))
        self.btnDecrypt.clicked.connect(lambda : self.get("d"))
        self.btnVerifyDecrypt.clicked.connect(lambda : self.get("vd"))
        self.btnInOpenAttachment.clicked.connect(lambda:self.openAttachmentOutbox(True))
        self.btnOutOpenAttachment.clicked.connect(self.openAttachmentOutbox)
        self.bntQuit.clicked.connect(Dialog.close)
        self.sourceDir = os.path.abspath(os.getcwd())
        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def goInboxPage(self):
        self.fillInbox()
        self.stackedWidget.setCurrentWidget(self.pageInbox)
        self.lineInDate.clear()
        self.lineInFromTo.clear()
        self.lineInTitle.clear()
        self.textInMessage.clear()
        self.btnVerify.setVisible(False)
        self.btnDecrypt.setVisible(False)
        self.btnVerifyDecrypt.setVisible(False)
        self.btnInOpenAttachment.setVisible(False)
        self.attachment_path = None
        self.message = None

    def goOutboxPage(self):
        self.fillOutbox()
        self.stackedWidget.setCurrentWidget(self.pageOutbox)
        self.lineOutDate.clear()
        self.lineOutToWho.clear()
        self.lineOutTitle.clear()
        self.textOutMessage.clear()
        self.btnOutOpenAttachment.setVisible(False)
        self.attachment_path = None
        self.message = None

    def goMessagePage(self):
        self.stackedWidget.setCurrentWidget(self.pageSendMessage)
        self.lineTitle.clear()
        self.textMessage.clear()
        self.textMessage.setPlaceholderText("Enter your message..")
        self.attachment_path = None
        self.message = None

    def get(self,method="vd"):
        """
        :param method: "v" for verify
                "d" for decrypt
                "vd" or "dv" for verify and decrypt
        """
        if method == "v":
            result, self.attachment_path = self.user.get_message(self.message)
            self.btnVerify.setVisible(False)
            if result:
                self.lblInInfo.setStyleSheet("color:rgb(85, 255, 0);margin-top:20px;font-size:25px;")
                self.lblInInfo.setText("Message is Verified..")
                if self.attachment_path:
                    self.btnInOpenAttachment.setVisible(True)
        elif method=="d" or method=="vd" or method=="dv":
            plain_text, self.attachment_path = self.user.get_message(self.message)
            self.textInMessage.setText(plain_text.decode("utf-8"))
            if method != "d":
                self.btnVerifyDecrypt.setVisible(False)
            else:
                self.btnDecrypt.setVisible(False)
            if self.attachment_path:
                self.btnInOpenAttachment.setVisible(True)

    def openAttachmentOutbox(self,flag=False):
        path = self.attachment_path
        os.startfile(path)
        if flag:
            time.sleep(1.5)
            os.remove(path)
        self.btnInOpenAttachment.setVisible(False)
        self.btnOutOpenAttachment.setVisible(False)

    def displayInbox(self):
        self.btnVerifyDecrypt.setVisible(False)
        self.btnDecrypt.setVisible(False)
        self.btnVerify.setVisible(False)
        self.btnInOpenAttachment.setVisible(False)
        self.lblInInfo.clear()
        index = self.listInbox.currentIndex().row() + 1
        if index != 0:
            inbox = self.user.get_inbox()
            message = inbox[len(inbox) - index]
            self.message = message
            self.lineInFromTo.setText(SqlQuery.select_user_by_id(message[1])[1])
            self.lineInTitle.setText(message[3])
            self.lineInDate.setText(message[13])
            if message[4] == 1:
                self.textInMessage.setText(message[5].decode("utf-8"))
                self.btnVerify.setVisible(True)
            elif message[4] == 2:
                self.textInMessage.setText(message[7].hex())
                self.btnDecrypt.setVisible(True)
            else:
                self.textInMessage.setText(message[7].hex())
                self.btnVerifyDecrypt.setVisible(True)
        else:
            self.lineInFromTo.clear()
            self.lineInDate.clear()
            self.lineInTitle.clear()

    def displayOutbox(self):
        index = self.listOutbox.currentIndex().row()
        if index != -1:
            outbox = self.user.outbox.sort_values(by="id", ascending=False)
            message = outbox.iloc[index]
            self.lineOutToWho.setText(message["receiver"])
            self.lineOutTitle.setText(message["title"])
            self.lineOutDate.setText(message["date"])
            if message["attachment"]!="-": # if attachment is not nan
                self.btnOutOpenAttachment.setVisible(True)
                self.attachment_path = f".info\{self.user.user_name}\outbox\{message['attachment']}"
            else:
                self.btnOutOpenAttachment.setVisible(False)
            self.textOutMessage.setText(message["message"])
        else:
            self.lineOutTitle.clear()
            self.lineOutDate.clear()
            self.lineOutToWho.clear()
            self.textOutMessage.clear()

    def send(self,method:str):
        """
        :param method: "s" for sign
                    "e" for encrypt
                    "se" or "es" for sign and encrypt
        """
        content = self.textMessage.toPlainText().encode("utf-8")
        if not content:
            self.lblInfo.setStyleSheet("color:red")
            self.lblInfo.setText("You have to write a message!!!")
            return False
        title = self.lineTitle.text()
        if not title:
            title = "Başlık yok."
        receiver_name = self.cbTowho.currentText()
        self.user.send_message(title, content, receiver_name, method, self.attachment_path)
        self.lblInfo.setStyleSheet("color:green;")
        self.lblInfo.setText("Message Sended..")
        self.attachment_path = None
        self.textMessage.clear()
        self.lineTitle.clear()
        self.lblInfo.clear()

    def addFile(self):
        self.lblInfo.clear()
        dlg = QtWidgets.QFileDialog()
        dir = self.sourceDir
        filename = QtWidgets.QFileDialog.getOpenFileName(dlg, "File Dialog", dir, "Files (*.txt *.png *.jpg *.bmp *.mp4 *.avi)")
        self.lblInfo.setStyleSheet("color:red")
        self.lblInfo.setText("Please wait until the file is uploaded!!")
        self.btnSign.setVisible(False)
        self.btnEncrypt.setVisible(False)
        self.btnEncryptSign.setVisible(False)
        self.btnAddFile.setVisible(False)
        if filename[0]:
            size = os.path.getsize(filename[0])
            if (size/(1024**2))<5:
                self.attachment_path = filename[0]
                self.lblInfo.setStyleSheet("color:green")
                self.lblInfo.setText("File added..")
                self.btnSign.setVisible(True)
                self.btnEncrypt.setVisible(True)
                self.btnEncryptSign.setVisible(True)
                self.btnAddFile.setVisible(True)
            else:
                self.attachment_path = None
                self.lblInfo.setStyleSheet("color:red")
                self.lblInfo.setText("Maximum file size is 5 Megabytes!! Your file is "+str(size/(1024**2))+" Megabytes.")

    def fillUsersToComboBox(self):
        users = SqlQuery.select_users()
        if len(users) == 1:
            self.lblInfo.setStyleSheet("color:orange;")
            self.lblInfo.setText("There is no user you can message yet :(")
        else:
            users = [user[1] for user in users]
            users.sort()
            users.remove(self.user.user_name)
            self.cbTowho.addItems(users)

    def fillOutbox(self):
        self.listOutbox.clear()
        outbox = self.user.outbox.sort_values(by="id", ascending=False)
        for index in range(len(outbox)):
            self.listOutbox.addItem(outbox.iloc[index]["receiver"])

    def fillInbox(self):
        self.listInbox.clear()
        inbox = self.user.get_inbox()
        for index in range(len(inbox) - 1, -1, -1):
            self.listInbox.addItem(SqlQuery.select_user_by_id(inbox[index][1])[1])

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblUser.setText(_translate("Dialog", "User : "))
        self.bntQuit.setText(_translate("Dialog", "Quit"))
        self.btnPageSendMessage.setText(_translate("Dialog", "New Message"))
        self.btnPageOutbox.setText(_translate("Dialog", "Outbox"))
        self.btnPageInbox.setText(_translate("Dialog", "Inbox"))
        self.lblAdd.setText(_translate("Dialog", "Add :"))
        self.btnAddFile.setText(_translate("Dialog", "File"))
        self.label.setText(_translate("Dialog", "To :"))
        self.label_2.setText(_translate("Dialog", "Title :"))
        self.btnEncrypt.setText(_translate("Dialog", "Encrypt and Send"))
        self.btnSign.setText(_translate("Dialog", "Sign and Send"))
        self.btnEncryptSign.setText(_translate("Dialog", "Encrypt, Sign and Send"))
        self.label_5.setText(_translate("Dialog", "Date :"))
        self.label_6.setText(_translate("Dialog", "Title :"))
        self.label_9.setText(_translate("Dialog", "From :"))
        self.btnDecrypt.setText(_translate("Dialog", "Decrypt"))
        self.btnVerify.setText(_translate("Dialog", "Verify"))
        self.btnVerifyDecrypt.setText(_translate("Dialog", "Verify ve Decrypt"))
        self.btnInOpenAttachment.setText(_translate("Dialog", "Open Attachment"))
        self.label_7.setText(_translate("Dialog", "Date :"))
        self.label_8.setText(_translate("Dialog", "Title :"))
        self.label_10.setText(_translate("Dialog", "To :"))
        self.btnOutOpenAttachment.setText(_translate("Dialog", "Open Attachment"))
